### ISSUE TITLE
showcase example runs frozen

### ISSUE THREAD

**Issue by ngortheone** [redox-os/orbtk#394]
When running `showcase` example on Linux X11 a window with all widget appears but it does not react on any input events (e.g. appears to be frozen)

Steps to reproduce:
- find linux workstation
- find X11 DE ( KDE 5.20 in my case)
- `cargo new showcase`
- copy contents from `showcase` example
- `cargo run`

observe the frozen window

**Comment by ngortheone** [comment]
correction: the app is not frozen, it consumes 100% CPU and is extremely slow (first reaction to a button press ~3 minutes)

**Comment by FloVanGH** [comment]
Same issue on release?

**Comment by ngortheone** [comment]
on release it still consumes 100% CPU, but input lag is significantly lower (less than a second, but still noticable)

Another observed effect: when app starts screen flickers and all window shadows disappear. When app is closed - another flicker and all desktop effects come back

**Comment by FloVanGH** [comment]
Check #392

**Comment by FloVanGH** [comment]
cpu load is fixed

**Comment by ngortheone** [comment]
@FloVanGH 
Unfortunately the bug is still reproducible on latest "develop" branch.

**Comment by FloVanGH** [comment]
Crazy. On my side the cpu load is down on idle to 1-3%. Same by kivimango. Have you tried run cargo clean before?

**Comment by ngortheone** [comment]
![orbtk-bug](https://user-images.githubusercontent.com/18271144/99151310-17e3a980-264f-11eb-9f1e-6ce6a669ab15.png)
I did 
`cargo clean; cargo update; cargo run`

On the screenshot you can see that "up" button on the input field is highlighted even though the mouse is not even in the window area (the lag) and no amount of clicking actually makes the number go up

**Comment by FloVanGH** [comment]
I tested it on gnome with x11 and the showcase uses 4% on idle. I will try to setup a machine with kde, maybe then I can reproduce it.

**Comment by ngortheone** [comment]
@FloVanGH 
I have just reproduced this issue on completely different system.
It is sway window manager (wayland) on Gentoo.

I am using latest develop branch.
Can you reopen this issue?
I want to help do debug this. What information would be useful?

**Comment by ngortheone** [comment]
moved to https://github.com/redox-os/orbtk/issues/408
